name: Upload Dev Build and Commit Artifact

on:
  push:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Package the VSCode extension (.vsix)
        run: npm run buildtag

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: List files after packaging
        run: |
          ls -al
          vsce ls

      - name: Upload .vsix as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'mythicscribe.vsix'
          path: '*.vsix'

      - name: Update tag to latest commit
        run: |
          git tag -f dev
          git push origin -f dev  

      - name: Get commit number
        id: get_commit_number
        run: |
          COMMIT_NUMBER=$(git rev-list --count HEAD)
          echo "number=$COMMIT_NUMBER" >> $GITHUB_OUTPUT

      - name: Get File Name
        id: get_file_name
        run: |
          FILE=$(ls *.vsix | head -n 1)
          BASENAME="${FILE%.*}"
          echo "Found .vsix file: $BASENAME"
          echo "name=$FILE" >> $GITHUB_OUTPUT
          echo "basename=$BASENAME" >> $GITHUB_OUTPUT
          echo "newname=${BASENAME}-${{ steps.get_commit_number.outputs.number }}.vsix" >> $GITHUB_OUTPUT
          ls -al

      - name: Generate release body
        id: generate_body
        run: |
          RELEASE_BODY=$(echo -e "The latest dev build, generated from the latest commit.\n\nEach commit also generates an artifact via the associated action. So, if you want to fetch a specific version, it is also possible to fetch that instead.\n\n**Build Information:**\n- Commit: $GITHUB_SHA\nBuild Number: ${{ steps.get_commit_number.outputs.number }}\n- Build Date: $(date +"%Y-%m-%dT%H:%M:%SZ")")
          echo "release_body<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Rename .vsix files
        run: |
          echo "Creating commit-numbered version: $NEWFILE"
          mv "${{ steps.get_file_name.outputs.name }}" "${{ steps.get_file_name.outputs.newname }}"
                    
          # List final files
          ls -al

      - name: Update Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          tag_name: dev
          name: Dev Build
          body: ${{ steps.generate_body.outputs.release_body }}
          generate_release_notes: true
          prerelease: true
          files: |
            ${{ steps.get_file_name.outputs.newname }}
          token: ${{ secrets.GITHUB_TOKEN }}